### ISSUE TITLE
plugins with no type (action, syntax, etc) not visible in API

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki-plugin-pluginrepo#123]
When you do a search for a plugin where the author set no types, the plugin will not be in the results.

**Comment by splitbrain** [comment]
Probably these are affected:

```
mysql> select plugin from plugins where type=0;
+-------------------------+
| plugin                  |
+-------------------------+
| passwordgenerator       |
| ipa                     |
| svgimg                  |
| readability             |
| toolbox                 |
| searchjump              |
| getraw                  |
| rotate                  |
| tocafterheadline        |
| dokuwikitemplatestretch |
| behave                  |
| tabbedsearchresults     |
| passwordgrey            |
| template-fine-tune      |
| revisionat              |
| boots3navi              |
+-------------------------+
16 rows in set (0.00 sec)
```

**Comment by Klap-in** [comment]
A live query is at: https://www.dokuwiki.org/teams:plugins_gardening#extensions_with_no_type_defined

Most of these queries ships only javascript.

**Comment by Klap-in** [comment]
Which api do you mean? There are three api's...

**Comment by splitbrain** [comment]
The one at http://www.dokuwiki.org/lib/plugins/pluginrepo/api.php - the problem happens for fulltext searches (using the `q` parameter).

**Comment by Klap-in** [comment]
```php
 // default to all extensions
        if($type == 0) {
            foreach(array_keys($this->types) as $t) $type += $t;
        }
```
```php
  public $types = array(
        1   => 'Syntax',
        2   => 'Admin',
        4   => 'Action',
        8   => 'Render',
        16  => 'Helper',
        32  => 'Template',
        64  => 'Remote',
        128 => 'Auth'
    );
```
So all is everything, but zero.

Further 
```php
WHERE (A.type & :type)
                       $namefilter
```
and later also at other places in `helper/repository.php` that comparison is made by looping over `$this->types`.

So current code assumes that always a type is given to a plugin. But this is not true for plugins with only some javascript.
Is it worth to assign a type to jsonly plugins? or do you prefer that such plugins without type, i.e. `type=0`, are supported?

**Comment by splitbrain** [comment]
To be honest, I am not sure how useful the type is anyway. I doubt anyone is ever using it to search, but I might be wrong. Personally I wouldn't mind depreciating it (removing it from the template and interface, ignore existing types).

Otherwise I would say if no type is explicitly requested, we should simply omit the where clause.
