### ISSUE TITLE
Ability to not display popularity on table component

### ISSUE THREAD

**Issue by AntoineTurmel** [splitbrain/dokuwiki-plugin-pluginrepo#31]
Should we put a switch to hide the popularity column on the table component ?

https://www.dokuwiki.org/plugin:repository:manual#pluginrepo_table_component

**Comment by Klap-in** [comment]
I vote for not implementing. If still desired, you can propose a pull request.

**Comment by splitbrain** [comment]
I agree with @Klap-in
