### ISSUE TITLE
Better remove old properties of plugins from database, if stored outside plugin: and template:

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki-plugin-pluginrepo#92]
Queries on the database show removed plugin entry blocks, which are not removed correctly from the database.

e.g. https://www.dokuwiki.org/teams:plugins_gardening#extensions_with_no_type_defined

**Comment by Klap-in** [comment]
How can removing of old plugin entry information from database been triggered if no plugin entry is in the text anymore?
Normally the metadata handling is triggered by existance of a pluginentry syntax in the text...

**Comment by splitbrain** [comment]
Hmm the data plugin does it in a action component https://github.com/splitbrain/dokuwiki-plugin-data/blob/master/action.php#L39

I thought we had something similar in this plugin?

**Comment by Klap-in** [comment]
Ah I made an exception for pages outside the template: and plugin: namespaces. Not that useful. I will fix it.
