### ISSUE TITLE
Call to a member function diff() on boolean

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki-plugin-pluginrepo#94]
PHP message: PHP Fatal error:  Call to a member function diff() on boolean in /var/www/wiki/htdocs/lib/plugins/pluginrepo/syntax/entry.php on line 114

introduces in: 05c95cb￼

As mentioned in https://github.com/splitbrain/dokuwiki/issues/1209 an effect of this is:

> The page is empty and no pagetools are displayed at:
> https://www.dokuwiki.org/plugin:keywords

**Comment by Klap-in** [comment]
the plugin entry at plugin:keywords has:
```
...
lastupdate : 25-11-2007
...
```
I assume this DD-MM-YYYY date format breaks the DateTime::createfromformat, because this function looks for `'Y-m-d'`.

**Comment by Klap-in** [comment]
solution: wrong date is age = 0?
@selfthinker or should we even assume that a wrong date is an too old date as well?

**Comment by splitbrain** [comment]
Yeah I guess we can drop everything before 2004
